# Generated by Django 3.2.3 on 2021-06-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Registration',
            new_name='Student_RegistrationModel',
        ),
    ]
