# Generated by Django 3.2.3 on 2021-06-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('uname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('repass', models.CharField(max_length=30)),
                ('age', models.IntegerField(max_length=45)),
            ],
        ),
    ]
